version: '3.6'
services:
  web:
    image: nginx:alpine
    container_name: web
    volumes:
      - "./nginx:/etc/nginx/conf.d"
      - "./log:/var/log/nginx/apps"
      - "./apps:/var/www/apps"
    ports:
      - "8000:8000" # app
    restart: always
  php:
    build: ./php
    container_name: php
    restart: always
    volumes:
      - "./apps:/var/www/apps"
  memcached:
    image: memcached:alpine
    container_name: memcached
    ports:
      - "11211:11211"
    restart: always
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=radiovolna
      - MYSQL_USER=neroot
      - MYSQL_PASSWORD=radiovolna
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    volumes:
      - "./mysql:/var/lib/mysql"
      - "./db-bak:/backup"
      - "./mysql-conf:/etc/mysql/conf.d"
    command: --ignore-db-dir=lost+found --innodb-use-native-aio=0
  adminer:
    image: adminer:standalone
    container_name: adminer
    restart: always
    ports:
      - "9999:8080"
  # redis:
  #     container_name: redis
  #     image: redis:4.0.5-alpine
  #     ports:
  #         - "6379:6379"
  #     volumes:
  #         - "./redis:/data"
  #     entrypoint: redis-server --appendonly yes
  #     restart: always

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - "./postgres:/data/postgres"
    ports:
      - "5432:5432"
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - "./pgadmin:/root/.pgadmin"
    ports:
      - "5050:5050"
    restart: unless-stopped